#ifndef FILECPP_QTWIDGETS_QTWIDGETSGLOBAL_H
#define FILECPP_QTWIDGETS_QTWIDGETSGLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QT_WIDGETS_LIBRARY
#  define QTWIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define QTWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // FILECPP_QTWIDGETS_QTWIDGETSGLOBAL_H
